### ISSUE TITLE
in-line error messages rather changing at the bottom of the page?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/mc-client-side-validation#5]
Modern UX tends to have helper text next to each field rather than at the bottom.

These pics make it look like an "on submit" type of error handling. But it would be good to get students trying "on blur" & "on keyup", etc. Especially because this is way more fiddle-y to get right than just `onSubmit`

**Comment by oliverjam** [comment]
Looks like this was added as a stretch goal in #19

**Comment by oliverjam** [comment]
Sorry it looks like this was partly resolved (the validation on blur) but we should still show the errors inline next to the inputs. I've raised #22 to track that
