### ISSUE TITLE
needs solution

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/mc-client-side-validation#9]
@sohilpandya do you have the code that you wrote to produce the image in the readme?

**Comment by sohilpandya** [comment]
It’s a sketch file. No code 😊

**Comment by jessicasalmon** [comment]
@jsms90 - I'm working on a solution now, though won't post it until the challenge is completed.

**Comment by jessicasalmon** [comment]
actually, my initial thoughts were that this challenge doesn't need a solution, because it's quite subjective as to what solution you come up with. I was just making one to run through the workshop properly. What are your thoughts on this @jsms90?

**Comment by jsms90** [comment]
Yeah I like getting away from the idea that there is a "right answer" to morning challenges. That's the whole point of casting solutions. Everyone is going to have something different and you all learn from each other.

But it still helps to have some kind of solution at the end, in case you were really stuck and didn't get anywhere. Even if you come back to it later and attempt it when you have more time, it helps to look through an example of what you _could_ have done.

But to get away from the "right answer" feeling of having just 1 solution, I think we should crowd source them. Just point up loads, from all the people who user test it over time.
